# Generated by Django 5.0.6 on 2025-08-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='completed',
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('pending', 'منتظر شروع'), ('in_progress', 'درحال انجام'), ('completed', 'کامل شده'), ('canceled', 'لغو شده')], default='pending', max_length=32),
        ),
    ]
