# Generated by Django 5.0.6 on 2025-08-19 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todo_completed_todo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.ForeignKey(default='pending', on_delete=django.db.models.deletion.CASCADE, to='todo.status'),
        ),
    ]
