# Generated by Django 5.0.6 on 2025-08-20 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_status_alter_todo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='name',
            field=models.CharField(default=1, max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='todo.status'),
        ),
    ]
